namespace Lendme.Core.Entities.Catalog;

public class ItemImage
{
    public string Url { get; set; }
    public string ThumbnailUrl { get; set; }
    public bool IsPrimary { get; set; }
    public int Order { get; set; }
    public string Description { get; set; }
    public List<string> AiTags { get; set; } // Generated by AI
    //public ImageMetadata Metadata { get; set; }
}