namespace Lendme.Core.Entities.Catalog;

public class ItemImage
{
    public Guid Id { get; set; }
    public Guid ItemDetailsId { get; set; } // Link to PostgreSQL
    public string Url { get; set; }
    public string ThumbnailUrl { get; set; }
    public bool IsPrimary { get; set; }
    public int Order { get; set; }
    public string Description { get; set; }
    public List<string> AiTags { get; set; } // Generated by AI
    public ItemDetails ItemDetails { get; set; }
    //public ImageMetadata Metadata { get; set; }
}